# tinyLMTune — Text Classification

This notebook demonstrates 3 ways to train TinyBERT for **classification** using tinyLMTune:

1. **Synthetic data** — auto-generated via Flan-T5/Mistral
2. **Benchmark data** — real HuggingFace dataset (rotten_tomatoes)
3. **Raw user data** — your own text, structured or unstructured

Each example runs the full pipeline: data → token analysis → search space recommendation → GA optimisation → model save → inference.

## Setup

In [1]:
import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(name)s | %(message)s")

# Install if needed (uncomment):
!pip install -e ../../tinylmtune_v2/

Obtaining fi
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (2.4.1.post300)
Requirement already satisfied: transformers>=4.30 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (4.51.3)
Collecting datasets==3.6.0 (from tinylmtune==2.0.0)
  Using cached datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: scikit-learn>=1.3 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (1.5.2)
Requirement already satisfied: numpy>=1.24 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (1.26.4)
Requirement already satisfied: sentencepiece>=0.1.99 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (0.1.99)
Requirement already satisfied: matplotlib>=3.7 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (3.10.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets==3.6.0->tinylmtune==2.0.0)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (3.5.0)
Collecting multiprocess<0.70.17 (from datasets==3.6.0->tinylmtune==2.0.0)
  Using cached multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /opt/conda/lib/python3.11/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (2024.10.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (0.30.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (6.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (1.4.7)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (2.9.0.post0)
Requirement already satisfied: scipy>=1.6.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (3.6.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (4.13.2)
Requirement already satisfied: sympy in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (1.13.3)
Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (3.4.2)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (0.5.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.11/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (3.9.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.7->tinylmtune==2.0.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch>=2.0->tinylmtune==2.0.0) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas->datasets==3.6.0->tinylmtune==2.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas->datasets==3.6.0->tinylmtune==2.0.0) (2025.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy->torch>=2.0->tinylmtune==2.0.0) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (6.4.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.20.0)
Requirement already satisfied: propcache>=0.2.1 in /opt/conda/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (0.3.1)
Using cached datasets-3.6.0-py3-none-any.whl (491 kB)
Using cached dill-0.3.8-py3-none-any.whl (116 kB)
Using cached multiprocess-0.70.16-py311-none-any.whl (143 kB)
Installing collected packages: dill, multiprocess, datasets, tinylmtune
  Attempting uninstall: dill
    Found existing installation: dill 0.4.0
    Uninstalling dill-0.4.0:
      Successfully uninstalled dill-0.4.0
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.18
    Uninstalling multiprocess-0.70.18:
      Successfully uninstalled multiprocess-0.70.18
  Attempting uninstall: datasets
    Found existing installation: datasets 2.2.1
    Uninstalling datasets-2.2.1:
      Successfully uninstalled datasets-2.2.1
  DEPRECATION: Legacy editable install of tinylmtune==2.0.0 from file:///home/sagemaker-user/SLM/tinylmtune_v2 (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for tinylmtune
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pathos 0.3.4 requires dill>=0.4.0, but you have dill 0.3.8 which is incompatible.
pathos 0.3.4 requires multiprocess>=0.70.18, but you have multiprocess 0.70.16 which is incompatible.
Successfully installed datasets-3.6.0 dill-0.3.8 multiprocess-0.70.16 tinylmtune-2.0.0

In [1]:
from tinylmtune import optimize_slm, TinyInference, print_token_analysis, print_recommendation, plot_results

2026-05-25 07:09:31.099722: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-25 07:09:31.112125: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-05-25 07:09:31.115976: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-05-25 07:09:31.125608: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
## Check search space recommendation before you start training 

print_recommendation(n_samples=200, task="classification")

=================================================================
  tinyLMTune — Search Space Recommendation
  Task: classification  |  Samples: 200  |  Max len: 128
  Parameters: 11
=================================================================

  Recommended search_space:
    learning_rate                   : (1e-05, 0.0005)
    batch_size                      : [4, 8, 16, 32]
    epochs                          : (3, 15)
    warmup_ratio                    : (0.0, 0.3)
    weight_decay                    : (0.0, 0.1)
    dropout                         : (0.05, 0.3)
    attention_dropout               : (0.05, 0.3)
    gradient_accumulation_steps     : [1, 2, 4, 8]
    lr_scheduler_type               : ['linear', 'cosine', 'cosine_with_restarts', 'constant_with_warmup']
    label_smoothing                 : (0.0, 0.1)
    max_grad_norm                   : (0.5, 5.0)

{'learning_rate': (1e-05, 0.0005),
 'batch_size': [4, 8, 16, 32],
 'epochs': (3, 15),
 'warmup_ratio': (0.0, 0.3),
 'weight_decay': (0.0, 0.1),
 'dropout': (0.05, 0.3),
 'attention_dropout': (0.05, 0.3),
 'gradient_accumulation_steps': [1, 2, 4, 8],
 'lr_scheduler_type': ['linear',
  'cosine',
  'cosine_with_restarts',
  'constant_with_warmup'],
 'label_smoothing': (0.0, 0.1),
 'max_grad_norm': (0.5, 5.0)}

---
## Example 1 — Synthetic Data (via Flan-T5)

No data needed. Flan-T5/Mistral generates training data from a topic prompt.

**Requirements:** Flan-T5 must be installed and running (`pip install sentencepiece`), with `mistral` model pulled (``).

In [3]:
best = optimize_slm(
    task="classification",
    corpus_prompt="Generate diverse product review sentiment examples",
    n_examples=200,
    labels="positive,negative,neutral",
    pop_size=4,
    generations=5,
    output_dir="models/classification_synthetic",
)
#print("Best config:", best)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [4]:
# Only displays, doesn't save
plot_results(best, save_dir="plots/synthetic_data")

{'fitness_progress': <Figure size 1000x600 with 1 Axes>,
 'parameter_scatter': <Figure size 1800x1800 with 12 Axes>,
 'scheduler_comparison': <Figure size 800x500 with 1 Axes>,
 'config_evolution': <Figure size 1800x1800 with 12 Axes>,
 'population_heatmap': <Figure size 1000x400 with 2 Axes>}

### Inference on synthetic model

In [5]:
model = TinyInference("models/classification_synthetic")

for text in [
    "Absolutely love this product, best purchase ever!",
    "Terrible quality, broke after one day.",
    "It's fine, does what it says.",
]:
    result = model.predict(text)
    print(f"Text:  {text}")
    print(f"Label: {result['label']}  Confidence: {result['confidence']:.1%}")
    print()

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Text:  Absolutely love this product, best purchase ever!
Label: positive  Confidence: 67.5%

Text:  Terrible quality, broke after one day.
Label: negative  Confidence: 60.5%

Text:  It's fine, does what it says.
Label: negative  Confidence: 47.2%

---
## Example 2 — Benchmark Data (rotten_tomatoes)

Uses a real HuggingFace dataset. No Flan-T5 needed.

### Load rotten_tomatoes dataset

In [6]:
from datasets import load_dataset

ds = load_dataset("rotten_tomatoes", split="train")
ds = ds.shuffle(seed=42).select(range(1000))  # use 300 samples

label_map = {0: "negative", 1: "positive"}
benchmark_data = [{"text": r["text"], "label": label_map[r["label"]]} for r in ds]

print(f"Loaded {len(benchmark_data)} records")
print(f"Sample: {benchmark_data[0]}")

Loaded 1000 records
Sample: {'text': '. . . plays like somebody spliced random moments of a chris rock routine into what is otherwise a cliche-riddled but self-serious spy thriller .', 'label': 'negative'}

### Analyze token lengths

In [7]:
print_token_analysis(benchmark_data, task="classification")

============================================================
  tinyLMTune — Token Length Analysis
  Task: classification  |  Samples: 1000
============================================================

  Token lengths:  min=3  mean=27  median=27  max=78

  Percentiles:
    p 50:   27 tokens
    p 75:   34 tokens
    p 90:   43 tokens
    p 95:   48 tokens
    p100:   78 tokens

  Truncation at standard lengths:
    max_len=  2: 100.0% truncated  ██████████████████████████████████████████████████
    max_len=  4:  99.9% truncated  █████████████████████████████████████████████████
    max_len=  8:  97.5% truncated  ████████████████████████████████████████████████
    max_len= 16:  83.2% truncated  █████████████████████████████████████████
    max_len= 24:  55.7% truncated  ███████████████████████████
    max_len= 32:  30.5% truncated  ███████████████
    max_len= 64:   0.2% truncated   ← recommended
    max_len= 96:   0.0% truncated
    max_len=128:   0.0% truncated
    max_len=192:   0.0% truncated
    max_len=256:   0.0% truncated
    max_len=384:   0.0% truncated
    max_len=512:   0.0% truncated

  Recommended max_len: 64
  GA search choices:   [32, 64, 96]

{'n_samples': 1000,
 'min': 3,
 'max': 78,
 'mean': 27,
 'median': 27,
 'p50': 27,
 'p75': 34,
 'p90': 43,
 'p95': 48,
 'p100': 78,
 'truncation_pct': {2: 100.0,
  4: 99.9,
  8: 97.5,
  16: 83.2,
  24: 55.7,
  32: 30.5,
  64: 0.2,
  96: 0.0,
  128: 0.0,
  192: 0.0,
  256: 0.0,
  384: 0.0,
  512: 0.0},
 'recommended_max_len': 64,
 'recommended_ga_choices': [32, 64, 96]}

### Check recommended search space

In [8]:
print_recommendation(n_samples=len(benchmark_data), task="classification")

=================================================================
  tinyLMTune — Search Space Recommendation
  Task: classification  |  Samples: 1000  |  Max len: 128
  Parameters: 11
=================================================================

  Recommended search_space:
    learning_rate                   : (5e-06, 0.0005)
    batch_size                      : [4, 8, 16, 32]
    epochs                          : (2, 10)
    warmup_ratio                    : (0.0, 0.3)
    weight_decay                    : (0.0, 0.05)
    dropout                         : (0.0, 0.2)
    attention_dropout               : (0.0, 0.2)
    gradient_accumulation_steps     : [1, 2, 4, 8]
    lr_scheduler_type               : ['linear', 'cosine', 'cosine_with_restarts', 'constant_with_warmup']
    label_smoothing                 : (0.0, 0.1)
    max_grad_norm                   : (0.5, 5.0)

{'learning_rate': (5e-06, 0.0005),
 'batch_size': [4, 8, 16, 32],
 'epochs': (2, 10),
 'warmup_ratio': (0.0, 0.3),
 'weight_decay': (0.0, 0.05),
 'dropout': (0.0, 0.2),
 'attention_dropout': (0.0, 0.2),
 'gradient_accumulation_steps': [1, 2, 4, 8],
 'lr_scheduler_type': ['linear',
  'cosine',
  'cosine_with_restarts',
  'constant_with_warmup'],
 'label_smoothing': (0.0, 0.1),
 'max_grad_norm': (0.5, 5.0)}

### Train with GA optimisation

In [25]:
best = optimize_slm(
    task="classification",
    user_data=benchmark_data,
    pop_size=6,
    generations=3,
    max_len = 64,
    output_dir="models/classification_benchmark",
)
print("Best config:", best)

2026-05-15 11:27:23,269 | tinylmtune._internal.pipeline | Model will be saved to: /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_benchmark
2026-05-15 11:27:23,270 | tinylmtune._internal.pipeline | user_data validated: 1000 / 1000 structured records
2026-05-15 11:27:23,270 | tinylmtune._internal.pipeline | Resolved 1000 structured records
2026-05-15 11:27:23,593 | tinylmtune._internal.token_analyzer | Token analysis: n=1000 min=3 mean=27 p95=48 max=78 → max_len=64, ga_choices=[32, 64, 96]
2026-05-15 11:27:23,598 | tinylmtune._internal.pipeline | Token analysis: p50=27 p95=48 max=78 → fixed max_len=64
2026-05-15 11:27:23,599 | tinylmtune._internal.dataset | Using 1000 user-provided records
2026-05-15 11:27:23,869 | tinylmtune._internal.dataset | Dataset: 800 train, 200 val
2026-05-15 11:27:23,900 | tinylmtune._internal.pipeline | Fixed max_len=64 | GA search space (11 params): ['learning_rate', 'batch_size', 'epochs', 'warmup_ratio', 'weight_decay', 'dropout', 'attention_dropout', 'gradient_accumulation_steps', 'lr_scheduler_type', 'label_smoothing', 'max_grad_norm']
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:27:24,171 | tinylmtune._internal.trainer | Training: lr=0.00032151626523665245 bs=4 epochs=6 dropout=0.02 attn_drop=0.15 grad_accum=1 scheduler=constant_with_warmup label_smooth=0.003 grad_norm=0.9

2026-05-15 11:27:46,529 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.6994220614433289, 'eval_accuracy': 0.475, 'eval_f1': 0.30593220338983046, 'eval_runtime': 0.6465, 'eval_samples_per_second': 309.34, 'eval_steps_per_second': 77.335, 'epoch': 3.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:27:46,730 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:28:05,344 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5134322643280029, 'eval_accuracy': 0.795, 'eval_f1': 0.794799276945093, 'eval_runtime': 0.657, 'eval_samples_per_second': 304.402, 'eval_steps_per_second': 76.1, 'epoch': 3.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:28:05,572 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=16 epochs=4 dropout=0.02 attn_drop=0.08 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.060 grad_norm=4.1

2026-05-15 11:28:15,152 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.49742648005485535, 'eval_accuracy': 0.785, 'eval_f1': 0.7843557200775604, 'eval_runtime': 0.1912, 'eval_samples_per_second': 1045.977, 'eval_steps_per_second': 67.988, 'epoch': 3.7199999999999998}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:28:15,360 | tinylmtune._internal.trainer | Training: lr=0.00036621723441343984 bs=4 epochs=8 dropout=0.13 attn_drop=0.18 grad_accum=4 scheduler=cosine label_smooth=0.070 grad_norm=0.7

2026-05-15 11:28:43,930 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.9389150738716125, 'eval_accuracy': 0.71, 'eval_f1': 0.7047619047619048, 'eval_runtime': 0.6525, 'eval_samples_per_second': 306.522, 'eval_steps_per_second': 76.631, 'epoch': 5.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:28:44,111 | tinylmtune._internal.trainer | Training: lr=0.0001178096464475157 bs=16 epochs=3 dropout=0.08 attn_drop=0.09 grad_accum=4 scheduler=cosine label_smooth=0.037 grad_norm=1.4

2026-05-15 11:28:51,703 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5858712792396545, 'eval_accuracy': 0.78, 'eval_f1': 0.7800881410256411, 'eval_runtime': 0.1968, 'eval_samples_per_second': 1016.504, 'eval_steps_per_second': 66.073, 'epoch': 2.8}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:28:51,935 | tinylmtune._internal.trainer | Training: lr=0.0001371540219143111 bs=4 epochs=4 dropout=0.09 attn_drop=0.05 grad_accum=2 scheduler=cosine_with_restarts label_smooth=0.084 grad_norm=4.0

2026-05-15 11:29:18,044 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.6470800638198853, 'eval_accuracy': 0.775, 'eval_f1': 0.7750506262656566, 'eval_runtime': 0.6413, 'eval_samples_per_second': 311.851, 'eval_steps_per_second': 77.963, 'epoch': 4.0}
2026-05-15 11:29:18,046 | tinylmtune._internal.ga_optimizer | Gen 1/3 — best=0.7948  avg=0.6908  worst=0.3059
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:29:18,248 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:29:55,259 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5274397134780884, 'eval_accuracy': 0.82, 'eval_f1': 0.8197467591196864, 'eval_runtime': 0.6574, 'eval_samples_per_second': 304.246, 'eval_steps_per_second': 76.061, 'epoch': 6.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:29:55,518 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=8 dropout=0.02 attn_drop=0.08 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.060 grad_norm=4.1

2026-05-15 11:30:41,743 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.6603146195411682, 'eval_accuracy': 0.795, 'eval_f1': 0.7951077570023278, 'eval_runtime': 0.2908, 'eval_samples_per_second': 687.866, 'eval_steps_per_second': 171.966, 'epoch': 8.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:30:41,935 | tinylmtune._internal.trainer | Training: lr=0.00019306401381548202 bs=4 epochs=10 dropout=0.18 attn_drop=0.06 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.060 grad_norm=0.8

2026-05-15 11:31:22,452 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.7894667983055115, 'eval_accuracy': 0.755, 'eval_f1': 0.755128653947138, 'eval_runtime': 0.2112, 'eval_samples_per_second': 946.778, 'eval_steps_per_second': 236.695, 'epoch': 7.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:31:22,622 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=16 epochs=4 dropout=0.02 attn_drop=0.08 grad_accum=2 scheduler=constant_with_warmup label_smooth=0.076 grad_norm=1.2

2026-05-15 11:31:32,479 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.6250910758972168, 'eval_accuracy': 0.79, 'eval_f1': 0.790126050420168, 'eval_runtime': 0.1633, 'eval_samples_per_second': 1224.705, 'eval_steps_per_second': 79.606, 'epoch': 4.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:31:32,701 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=4 epochs=7 dropout=0.11 attn_drop=0.03 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:31:56,855 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5128977298736572, 'eval_accuracy': 0.805, 'eval_f1': 0.805102398039559, 'eval_runtime': 0.6336, 'eval_samples_per_second': 315.653, 'eval_steps_per_second': 78.913, 'epoch': 4.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:31:57,116 | tinylmtune._internal.trainer | Training: lr=0.0001178096464475157 bs=8 epochs=4 dropout=0.02 attn_drop=0.08 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.072 grad_norm=4.1

2026-05-15 11:32:10,198 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.49758484959602356, 'eval_accuracy': 0.805, 'eval_f1': 0.8050439640271548, 'eval_runtime': 0.3461, 'eval_samples_per_second': 577.903, 'eval_steps_per_second': 72.238, 'epoch': 4.0}
2026-05-15 11:32:10,199 | tinylmtune._internal.ga_optimizer | Gen 2/3 — best=0.8197  avg=0.7950  worst=0.7551
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:32:10,370 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:32:41,691 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5274397134780884, 'eval_accuracy': 0.82, 'eval_f1': 0.8197467591196864, 'eval_runtime': 0.6908, 'eval_samples_per_second': 289.523, 'eval_steps_per_second': 72.381, 'epoch': 6.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:32:41,900 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=8 dropout=0.11 attn_drop=0.03 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:33:24,044 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.694821834564209, 'eval_accuracy': 0.795, 'eval_f1': 0.7949434539481933, 'eval_runtime': 0.6879, 'eval_samples_per_second': 290.759, 'eval_steps_per_second': 72.69, 'epoch': 8.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:33:24,228 | tinylmtune._internal.trainer | Training: lr=0.00019306401381548202 bs=4 epochs=10 dropout=0.18 attn_drop=0.06 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=0.8

2026-05-15 11:34:00,800 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.7855801582336426, 'eval_accuracy': 0.745, 'eval_f1': 0.7438999470218723, 'eval_runtime': 0.3138, 'eval_samples_per_second': 637.428, 'eval_steps_per_second': 159.357, 'epoch': 7.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:34:00,983 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=4 epochs=7 dropout=0.11 attn_drop=0.03 grad_accum=2 scheduler=constant_with_warmup label_smooth=0.076 grad_norm=1.2

2026-05-15 11:34:44,009 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.8324633240699768, 'eval_accuracy': 0.715, 'eval_f1': 0.7147220624640545, 'eval_runtime': 0.6662, 'eval_samples_per_second': 300.199, 'eval_steps_per_second': 75.05, 'epoch': 7.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:34:44,227 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=4 epochs=7 dropout=0.11 attn_drop=0.03 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:35:20,429 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.6374549269676208, 'eval_accuracy': 0.795, 'eval_f1': 0.7949436235905898, 'eval_runtime': 0.6732, 'eval_samples_per_second': 297.096, 'eval_steps_per_second': 74.274, 'epoch': 7.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:35:20,639 | tinylmtune._internal.trainer | Training: lr=0.0001178096464475157 bs=8 epochs=7 dropout=0.11 attn_drop=0.03 grad_accum=4 scheduler=linear label_smooth=0.072 grad_norm=1.2

2026-05-15 11:35:42,001 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.48560279607772827, 'eval_accuracy': 0.81, 'eval_f1': 0.809885588117222, 'eval_runtime': 0.3648, 'eval_samples_per_second': 548.174, 'eval_steps_per_second': 68.522, 'epoch': 6.0}
2026-05-15 11:35:42,002 | tinylmtune._internal.ga_optimizer | Gen 3/3 — best=0.8197  avg=0.7797  worst=0.7147
2026-05-15 11:35:42,003 | tinylmtune._internal.pipeline | Best config (fitness=0.8197): {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22, 'fitness': 0.8197467591196864}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 11:35:42,231 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-15 11:36:12,124 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 0.5960086584091187, 'eval_accuracy': 0.78, 'eval_f1': 0.7796904833685057, 'eval_runtime': 0.6764, 'eval_samples_per_second': 295.682, 'eval_steps_per_second': 73.92, 'epoch': 6.0}
2026-05-15 11:36:12,277 | tinylmtune._internal.inference | Model saved → /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_benchmark

Best config: {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22, 'fitness': 0.8197467591196864, 'max_len': 64, 'task': 'classification', 'output_dir': '/home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_benchmark', 'ga_history': [{'generation': 1, 'individual': 0, 'fitness': 0.30593220338983046, 'learning_rate': 0.00032151626523665245, 'batch_size': 4, 'epochs': 6, 'warmup_ratio': 0.073, 'weight_decay': 0.014, 'dropout': 0.02, 'attention_dropout': 0.148, 'gradient_accumulation_steps': 1, 'lr_scheduler_type': 'constant_with_warmup', 'label_smoothing': 0.003, 'max_grad_norm': 0.92}, {'generation': 1, 'individual': 1, 'fitness': 0.794799276945093, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 1, 'individual': 2, 'fitness': 0.7843557200775604, 'learning_rate': 0.00021419412708598376, 'batch_size': 16, 'epochs': 4, 'warmup_ratio': 0.065, 'weight_decay': 0.0763, 'dropout': 0.02, 'attention_dropout': 0.076, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.06, 'max_grad_norm': 4.13}, {'generation': 1, 'individual': 3, 'fitness': 0.7047619047619048, 'learning_rate': 0.00036621723441343984, 'batch_size': 4, 'epochs': 8, 'warmup_ratio': 0.024, 'weight_decay': 0.0293, 'dropout': 0.126, 'attention_dropout': 0.177, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine', 'label_smoothing': 0.07, 'max_grad_norm': 0.71}, {'generation': 1, 'individual': 4, 'fitness': 0.7800881410256411, 'learning_rate': 0.0001178096464475157, 'batch_size': 16, 'epochs': 3, 'warmup_ratio': 0.257, 'weight_decay': 0.0866, 'dropout': 0.076, 'attention_dropout': 0.091, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine', 'label_smoothing': 0.037, 'max_grad_norm': 1.44}, {'generation': 1, 'individual': 5, 'fitness': 0.7750506262656566, 'learning_rate': 0.0001371540219143111, 'batch_size': 4, 'epochs': 4, 'warmup_ratio': 0.16, 'weight_decay': 0.0245, 'dropout': 0.092, 'attention_dropout': 0.054, 'gradient_accumulation_steps': 2, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.084, 'max_grad_norm': 3.99}, {'generation': 2, 'individual': 0, 'fitness': 0.8197467591196864, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 2, 'individual': 1, 'fitness': 0.7951077570023278, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 8, 'warmup_ratio': 0.028, 'weight_decay': 0.0602, 'dropout': 0.02, 'attention_dropout': 0.076, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.06, 'max_grad_norm': 4.13}, {'generation': 2, 'individual': 2, 'fitness': 0.755128653947138, 'learning_rate': 0.00019306401381548202, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.0459, 'dropout': 0.184, 'attention_dropout': 0.059, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.06, 'max_grad_norm': 0.81}, {'generation': 2, 'individual': 3, 'fitness': 0.790126050420168, 'learning_rate': 0.00021419412708598376, 'batch_size': 16, 'epochs': 4, 'warmup_ratio': 0.08, 'weight_decay': 0.0763, 'dropout': 0.02, 'attention_dropout': 0.076, 'gradient_accumulation_steps': 2, 'lr_scheduler_type': 'constant_with_warmup', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 2, 'individual': 4, 'fitness': 0.805102398039559, 'learning_rate': 0.00021419412708598376, 'batch_size': 4, 'epochs': 7, 'warmup_ratio': 0.15, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.028, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 2, 'individual': 5, 'fitness': 0.8050439640271548, 'learning_rate': 0.0001178096464475157, 'batch_size': 8, 'epochs': 4, 'warmup_ratio': 0.065, 'weight_decay': 0.0382, 'dropout': 0.02, 'attention_dropout': 0.076, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.072, 'max_grad_norm': 4.13}, {'generation': 3, 'individual': 0, 'fitness': 0.8197467591196864, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 3, 'individual': 1, 'fitness': 0.7949434539481933, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 8, 'warmup_ratio': 0.028, 'weight_decay': 0.0602, 'dropout': 0.109, 'attention_dropout': 0.028, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 3, 'individual': 2, 'fitness': 0.7438999470218723, 'learning_rate': 0.00019306401381548202, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.0459, 'dropout': 0.184, 'attention_dropout': 0.059, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 0.81}, {'generation': 3, 'individual': 3, 'fitness': 0.7147220624640545, 'learning_rate': 0.00021419412708598376, 'batch_size': 4, 'epochs': 7, 'warmup_ratio': 0.08, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.028, 'gradient_accumulation_steps': 2, 'lr_scheduler_type': 'constant_with_warmup', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 3, 'individual': 4, 'fitness': 0.7949436235905898, 'learning_rate': 0.00021419412708598376, 'batch_size': 4, 'epochs': 7, 'warmup_ratio': 0.15, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.028, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 3, 'individual': 5, 'fitness': 0.809885588117222, 'learning_rate': 0.0001178096464475157, 'batch_size': 8, 'epochs': 7, 'warmup_ratio': 0.15, 'weight_decay': 0.0382, 'dropout': 0.109, 'attention_dropout': 0.028, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.072, 'max_grad_norm': 1.22}], 'ga_generation_stats': [{'generation': 1, 'best_fitness': 0.794799276945093, 'worst_fitness': 0.30593220338983046, 'avg_fitness': 0.6908313120776143, 'std_fitness': 0.17462207396153806, 'best_config': {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}}, {'generation': 2, 'best_fitness': 0.8197467591196864, 'worst_fitness': 0.755128653947138, 'avg_fitness': 0.7950425970926723, 'std_fitness': 0.020119733644392474, 'best_config': {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}}, {'generation': 3, 'best_fitness': 0.8197467591196864, 'worst_fitness': 0.7147220624640545, 'avg_fitness': 0.7796902390436031, 'std_fitness': 0.0376019041681389, 'best_config': {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}}]}

### Visualize GA Results

5 plots showing how the GA searched for the best hyperparameters:
1. **Fitness progress** — best/avg/worst per generation
2. **Parameter scatter** — each param vs fitness (best = red star)
3. **Scheduler comparison** — box plot by LR scheduler type
4. **Config evolution** — how the best config changed over generations
5. **Population heatmap** — all individuals in the last generation

In [26]:
from tinylmtune import plot_results, print_best_config_table

# Print formatted best config
print_best_config_table(best)

# Generate all 5 plots
figs = plot_results(best, save_dir="plots/benchmark")

2026-05-15 11:36:47,023 | tinylmtune._internal.visualizer | Saved: plots/benchmark/01_fitness_progress.png

=======================================================
  Best Configuration — F1 Score: 0.8197
=======================================================
  learning_rate                      : 0.000120167
  batch_size                         : 4
  epochs                             : 10
  warmup_ratio                       : 0.06
  weight_decay                       : 0.065
  dropout                            : 0.109
  attention_dropout                  : 0.044
  gradient_accumulation_steps        : 4
  lr_scheduler_type                  : linear
  label_smoothing                    : 0.076
  max_grad_norm                      : 1.22
  max_len (fixed from data)          : 64
  output_dir                         : /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_benchmark

2026-05-15 11:36:48,417 | tinylmtune._internal.visualizer | Saved: plots/benchmark/02_parameter_scatter.png
2026-05-15 11:36:48,541 | tinylmtune._internal.visualizer | Saved: plots/benchmark/03_scheduler_comparison.png
2026-05-15 11:36:49,865 | tinylmtune._internal.visualizer | Saved: plots/benchmark/04_config_evolution.png
2026-05-15 11:36:50,122 | tinylmtune._internal.visualizer | Saved: plots/benchmark/05_population_heatmap.png
2026-05-15 11:36:50,123 | tinylmtune._internal.visualizer | Generated 5 plots

### Inference on benchmark model

In [28]:
model = TinyInference("models/classification_benchmark")

test_texts = [
    "A stunning visual masterpiece with brilliant performances.",
    "Predictable plot and terrible dialogue throughout.",
    "An average film that neither excels nor disappoints.",
]
for text in test_texts:
    result = model.predict(text)
    print(f"{result['label']:10s} ({result['confidence']:.1%})  {text}")

2026-05-15 11:37:22,995 | tinylmtune._internal.inference | Loaded classification model from models/classification_benchmark
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

positive   (94.3%)  A stunning visual masterpiece with brilliant performances.
positive   (60.6%)  Predictable plot and terrible dialogue throughout.
negative   (93.7%)  An average film that neither excels nor disappoints.

---
## Example 3 — Raw User Data

Three sub-examples showing different input formats:
- **3a.** Structured dicts (correct format)
- **3b.** Raw text strings (auto-labelled via Flan-T5)
- **3c.** Wrong-format dicts (auto-detected and converted)

### 3a. Structured dicts (used directly, no Flan-T5)

In [15]:
my_data = [
    {"text": "Absolutely loved this product!", "label": "positive"},
    {"text": "Best purchase I've made this year", "label": "positive"},
    {"text": "Works great, highly recommend", "label": "positive"},
    {"text": "Exceeded all my expectations", "label": "positive"},
    {"text": "Amazing quality for the price", "label": "positive"},
    {"text": "Will definitely buy again", "label": "positive"},
    {"text": "Perfect gift, they loved it", "label": "positive"},
    {"text": "Five stars, no complaints at all", "label": "positive"},
    {"text": "Total waste of money", "label": "negative"},
    {"text": "Broke after just two days", "label": "negative"},
    {"text": "Worst product I've ever bought", "label": "negative"},
    {"text": "Completely unusable, returning it", "label": "negative"},
    {"text": "Poor quality, very disappointed", "label": "negative"},
    {"text": "Do not buy, save your money", "label": "negative"},
    {"text": "Terrible customer service too", "label": "negative"},
    {"text": "Fell apart on first use", "label": "negative"},
    {"text": "It's okay, nothing special", "label": "neutral"},
    {"text": "Average product, does the job", "label": "neutral"},
    {"text": "Meets expectations, no more no less", "label": "neutral"},
    {"text": "Fine for the price, not amazing", "label": "neutral"},
]

best = optimize_slm(
    task="classification",
    user_data=my_data,
    pop_size=4,
    generations=2,
    output_dir="models/classification_user",
)

2026-05-15 08:41:55,267 | tinylmtune._internal.pipeline | Model will be saved to: /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_user
2026-05-15 08:41:55,268 | tinylmtune._internal.pipeline | user_data validated: 20 / 20 structured records
2026-05-15 08:41:55,268 | tinylmtune._internal.pipeline | Resolved 20 structured records
2026-05-15 08:41:55,478 | tinylmtune._internal.token_analyzer | Token analysis: n=20 min=6 mean=7 p95=9 max=10 → max_len=32, ga_choices=[32]
2026-05-15 08:41:55,481 | tinylmtune._internal.pipeline | Token analysis: p50=7 p95=9 max=10 → fixed max_len=32
2026-05-15 08:41:55,482 | tinylmtune._internal.dataset | Using 20 user-provided records
2026-05-15 08:41:55,668 | tinylmtune._internal.dataset | Dataset: 16 train, 4 val
2026-05-15 08:41:55,670 | tinylmtune._internal.pipeline | Fixed max_len=32 | GA search space (11 params): ['learning_rate', 'batch_size', 'epochs', 'warmup_ratio', 'weight_decay', 'dropout', 'attention_dropout', 'gradient_accumulation_steps', 'lr_scheduler_type', 'label_smoothing', 'max_grad_norm']
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:41:55,894 | tinylmtune._internal.trainer | Training: lr=0.00013149109170699792 bs=4 epochs=13 dropout=0.13 attn_drop=0.32 grad_accum=4 scheduler=linear label_smooth=0.118 grad_norm=0.6

2026-05-15 08:41:57,552 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.1012930870056152, 'eval_accuracy': 0.25, 'eval_f1': 0.1, 'eval_runtime': 0.0083, 'eval_samples_per_second': 483.535, 'eval_steps_per_second': 120.884, 'epoch': 4.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:41:57,721 | tinylmtune._internal.trainer | Training: lr=2.7802095573702566e-05 bs=4 epochs=5 dropout=0.31 attn_drop=0.23 grad_accum=2 scheduler=cosine_with_restarts label_smooth=0.162 grad_norm=0.5

2026-05-15 08:42:01,316 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.0951111316680908, 'eval_accuracy': 0.75, 'eval_f1': 0.6428571428571428, 'eval_runtime': 0.0077, 'eval_samples_per_second': 517.464, 'eval_steps_per_second': 129.366, 'epoch': 3.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:01,479 | tinylmtune._internal.trainer | Training: lr=0.00016310565784823352 bs=8 epochs=15 dropout=0.33 attn_drop=0.13 grad_accum=2 scheduler=linear label_smooth=0.072 grad_norm=2.0

2026-05-15 08:42:06,588 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.0990806818008423, 'eval_accuracy': 0.25, 'eval_f1': 0.1, 'eval_runtime': 0.009, 'eval_samples_per_second': 443.021, 'eval_steps_per_second': 110.755, 'epoch': 4.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:06,756 | tinylmtune._internal.trainer | Training: lr=6.0258964772182484e-05 bs=4 epochs=19 dropout=0.21 attn_drop=0.27 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.115 grad_norm=3.7

2026-05-15 08:42:10,535 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.0950015783309937, 'eval_accuracy': 0.75, 'eval_f1': 0.6428571428571428, 'eval_runtime': 0.0083, 'eval_samples_per_second': 480.778, 'eval_steps_per_second': 120.194, 'epoch': 3.0}
2026-05-15 08:42:10,536 | tinylmtune._internal.ga_optimizer | Gen 1/2 — best=0.6429  avg=0.3714  worst=0.1000
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:10,785 | tinylmtune._internal.trainer | Training: lr=2.7802095573702566e-05 bs=4 epochs=5 dropout=0.31 attn_drop=0.23 grad_accum=2 scheduler=cosine_with_restarts label_smooth=0.162 grad_norm=0.5

2026-05-15 08:42:14,488 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.1051615476608276, 'eval_accuracy': 0.0, 'eval_f1': 0.0, 'eval_runtime': 0.0078, 'eval_samples_per_second': 513.379, 'eval_steps_per_second': 128.345, 'epoch': 3.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:14,655 | tinylmtune._internal.trainer | Training: lr=2.7802095573702566e-05 bs=4 epochs=18 dropout=0.31 attn_drop=0.23 grad_accum=2 scheduler=cosine_with_restarts label_smooth=0.162 grad_norm=0.5

2026-05-15 08:42:18,448 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.1048715114593506, 'eval_accuracy': 0.0, 'eval_f1': 0.0, 'eval_runtime': 0.0109, 'eval_samples_per_second': 368.099, 'eval_steps_per_second': 92.025, 'epoch': 3.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:18,611 | tinylmtune._internal.trainer | Training: lr=8.218618712109411e-05 bs=4 epochs=5 dropout=0.38 attn_drop=0.19 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.115 grad_norm=0.8

2026-05-15 08:42:23,934 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.0988287925720215, 'eval_accuracy': 0.25, 'eval_f1': 0.1, 'eval_runtime': 0.0076, 'eval_samples_per_second': 525.981, 'eval_steps_per_second': 131.495, 'epoch': 5.0}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:24,104 | tinylmtune._internal.trainer | Training: lr=7.750143304322909e-05 bs=4 epochs=19 dropout=0.21 attn_drop=0.24 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.115 grad_norm=2.0

2026-05-15 08:42:30,346 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.1024627685546875, 'eval_accuracy': 0.25, 'eval_f1': 0.1, 'eval_runtime': 0.0097, 'eval_samples_per_second': 411.681, 'eval_steps_per_second': 102.92, 'epoch': 5.0}
2026-05-15 08:42:30,348 | tinylmtune._internal.ga_optimizer | Gen 2/2 — best=0.1000  avg=0.0500  worst=0.0000
2026-05-15 08:42:30,348 | tinylmtune._internal.pipeline | Best config (fitness=0.6429): {'learning_rate': 2.7802095573702566e-05, 'batch_size': 4, 'epochs': 5, 'warmup_ratio': 0.112, 'weight_decay': 0.1074, 'dropout': 0.31, 'attention_dropout': 0.226, 'gradient_accumulation_steps': 2, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.162, 'max_grad_norm': 0.53, 'fitness': 0.6428571428571428}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-15 08:42:30,514 | tinylmtune._internal.trainer | Training: lr=2.7802095573702566e-05 bs=4 epochs=5 dropout=0.31 attn_drop=0.23 grad_accum=2 scheduler=cosine_with_restarts label_smooth=0.162 grad_norm=0.5

2026-05-15 08:42:32,205 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.1049959659576416, 'eval_accuracy': 0.25, 'eval_f1': 0.1, 'eval_runtime': 0.0081, 'eval_samples_per_second': 496.794, 'eval_steps_per_second': 124.198, 'epoch': 5.0}
2026-05-15 08:42:32,285 | tinylmtune._internal.inference | Model saved → /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_user

### 3b. Raw text strings (requires Flan-T5)

In [ ]:
# Raw strings — Flan-T5 will label them automatically
raw_texts = [
    "This movie was absolutely wonderful and heartwarming!",
    "A complete waste of two hours of my life.",
    "The acting was superb but the plot dragged on.",
    "One of the best films I've seen this year!",
    "Terribly written with no character development.",
    "Decent entertainment, nothing groundbreaking.",
]

labels = "positive,negative,neutral"

best = optimize_slm(
    task="classification",
    user_data=raw_texts,
    labels= labels,
    pop_size=4,
    generations=1,
    output_dir="models/classification_raw",
)

### 3c. Wrong-format dicts (requires Flan-T5)

In [ ]:
# Dicts with wrong keys — pipeline auto-detects and converts
wrong_format = [
    {"content": "This restaurant has amazing food and great service!"},
    {"content": "Worst dining experience ever, never going back."},
    {"content": "The food was okay but overpriced for the quality."},
    {"content": "Absolutely delicious, my new favourite place!"},
    {"content": "Rude staff and cold food, very disappointed."},
    {"content": "Average meal, nothing to write home about."},
]

# Pipeline detects "content" key, extracts text, labels via Flan-T5
best = optimize_slm(
    task="classification",
    user_data=wrong_format,
    labels="positive,negative,neutral",
    pop_size=4,
    generations=1,
    output_dir="models/classification_wrong",
)

### Visualize user data results

In [16]:
# Plot results from structured data training (Example 3a)
from tinylmtune import plot_results, print_best_config_table
print_best_config_table(best)
figs = plot_results(best, save_dir="plots/user_data")

2026-05-15 08:44:27,668 | tinylmtune._internal.visualizer | Saved: plots/user_data/01_fitness_progress.png

=======================================================
  Best Configuration — F1 Score: 0.6429
=======================================================
  learning_rate                      : 2.78021e-05
  batch_size                         : 4
  epochs                             : 5
  warmup_ratio                       : 0.112
  weight_decay                       : 0.1074
  dropout                            : 0.31
  attention_dropout                  : 0.226
  gradient_accumulation_steps        : 2
  lr_scheduler_type                  : cosine_with_restarts
  label_smoothing                    : 0.162
  max_grad_norm                      : 0.53
  max_len (fixed from data)          : 32
  output_dir                         : /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/classification_user

2026-05-15 08:44:28,929 | tinylmtune._internal.visualizer | Saved: plots/user_data/02_parameter_scatter.png
2026-05-15 08:44:29,035 | tinylmtune._internal.visualizer | Saved: plots/user_data/03_scheduler_comparison.png
2026-05-15 08:44:30,348 | tinylmtune._internal.visualizer | Saved: plots/user_data/04_config_evolution.png
2026-05-15 08:44:30,558 | tinylmtune._internal.visualizer | Saved: plots/user_data/05_population_heatmap.png
2026-05-15 08:44:30,558 | tinylmtune._internal.visualizer | Generated 5 plots

### Inference

In [18]:
model = TinyInference("models/classification_user")
result = model.predict("This is the best thing I've ever purchased!")
print(result)

2026-05-15 08:46:37,173 | tinylmtune._internal.inference | Loaded classification model from models/classification_user
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'label': 'positive', 'confidence': 0.3405956029891968, 'probabilities': {'negative': 0.32547882199287415, 'neutral': 0.3339255750179291, 'positive': 0.3405956029891968}}

---
## Summary

| Example | Data source | Flan-T5 needed | Best for |
|---------|-------------|---------------|----------|
| Synthetic | Auto-generated | Yes | Quick prototyping |
| Benchmark | rotten_tomatoes | No | Reproducible evaluation |
| User data | Your own text | Depends on format | Production use |

The GA searches 11 hyperparameters: `learning_rate`, `batch_size`, `epochs`, `warmup_ratio`, `weight_decay`, `dropout`, `attention_dropout`, `gradient_accumulation_steps`, `lr_scheduler_type`, `label_smoothing`, `max_grad_norm`.

`max_len` is automatically determined from your data's token length distribution (p95 percentile).