# tinyLMTune — Question Answering

This notebook demonstrates 3 ways to train TinyBERT for **qna** using tinyLMTune:

1. **Synthetic data** — auto-generated via Flan-T5/Mistral
2. **Benchmark data** — real HuggingFace dataset (SQuAD)
3. **Raw user data** — your own text, structured or unstructured

Each example runs the full pipeline: data → token analysis → search space recommendation → GA optimisation → model save → inference.

## Setup

In [1]:
import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(name)s | %(message)s")

# Install if needed (uncomment):
!pip install -e ../../tinylmtune_v2/

from tinylmtune import optimize_slm, TinyInference, print_token_analysis, print_recommendation

Obtaining file:///home/sagemaker-user/SLM/tinylmtune_v2
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (2.4.1.post300)
Requirement already satisfied: transformers>=4.30 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (4.51.3)
Requirement already satisfied: datasets==3.6.0 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (3.6.0)
Requirement already satisfied: scikit-learn>=1.3 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (1.5.2)
Requirement already satisfied: numpy>=1.24 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (1.26.4)
Requirement already satisfied: sentencepiece>=0.1.99 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (0.1.99)
Requirement already satisfied: matplotlib>=3.7 in /opt/conda/lib/python3.11/site-packages (from tinylmtune==2.0.0) (3.10.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (0.3.8)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /opt/conda/lib/python3.11/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (2024.10.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (0.30.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.11/site-packages (from datasets==3.6.0->tinylmtune==2.0.0) (6.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (1.4.7)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7->tinylmtune==2.0.0) (2.9.0.post0)
Requirement already satisfied: scipy>=1.6.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.3->tinylmtune==2.0.0) (3.6.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (4.13.2)
Requirement already satisfied: sympy in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (1.13.3)
Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (3.4.2)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch>=2.0->tinylmtune==2.0.0) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.11/site-packages (from transformers>=4.30->tinylmtune==2.0.0) (0.5.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.11/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (3.9.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.7->tinylmtune==2.0.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests>=2.32.2->datasets==3.6.0->tinylmtune==2.0.0) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch>=2.0->tinylmtune==2.0.0) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas->datasets==3.6.0->tinylmtune==2.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas->datasets==3.6.0->tinylmtune==2.0.0) (2025.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy->torch>=2.0->tinylmtune==2.0.0) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (6.4.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (1.20.0)
Requirement already satisfied: propcache>=0.2.1 in /opt/conda/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->tinylmtune==2.0.0) (0.3.1)
Installing collected packages: tinylmtune
  Attempting uninstall: tinylmtune
    Found existing installation: tinylmtune 2.0.0
    Uninstalling tinylmtune-2.0.0:
      Successfully uninstalled tinylmtune-2.0.0
  DEPRECATION: Legacy editable install of tinylmtune==2.0.0 from file:///home/sagemaker-user/SLM/tinylmtune_v2 (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for tinylmtune
Successfully installed tinylmtune-2.0.0

2026-05-18 06:42:09,047 | datasets | PyTorch version 2.4.1.post300 available.
2026-05-18 06:42:09,049 | datasets | TensorFlow version 2.17.0 available.
2026-05-18 06:42:10.069024: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-18 06:42:10.081349: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-05-18 06:42:10.085896: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-05-18 06:42:10.095517: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

---
## Example 1 — Synthetic Data (via Flan-T5)

No data needed. Flan-T5/Mistral generates training data from a topic prompt.

**Requirements:** Flan-T5 must be installed and running (`pip install sentencepiece`), with `mistral` model pulled (``).

In [11]:
best = optimize_slm(
    task="qna",
    corpus_prompt="Generate question-answer-context samples about world history and geography",
    n_examples=1000,
    max_len=8,
    pop_size=4,
    generations=2,
    output_dir="models/qna_synthetic",
)
print("Best config:", best)

2026-05-18 07:00:16,418 | tinylmtune._internal.pipeline | Model will be saved to: /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/qna_synthetic
2026-05-18 07:00:16,418 | tinylmtune._internal.pipeline | No user data — generating synthetic corpus
2026-05-18 07:00:16,419 | tinylmtune._internal.corpus_gen | Generating 1000 qna examples about 'Generate question-answer-context samples about world history and geography' using google/flan-t5-small ...
2026-05-18 07:00:16,419 | tinylmtune._internal.llm_backend | Loading LLM: google/flan-t5-small ...
2026-05-18 07:00:16,733 | tinylmtune._internal.llm_backend | LLM loaded on cuda (76961152 params)
2026-05-18 07:00:35,598 | tinylmtune._internal.corpus_gen | Generated 50 / 1000 examples (50 valid so far)
2026-05-18 07:00:53,639 | tinylmtune._internal.corpus_gen | Generated 100 / 1000 examples (96 valid so far)
2026-05-18 07:01:12,631 | tinylmtune._internal.corpus_gen | Generated 150 / 1000 examples (144 valid so far)
2026-05-18 07:01:33,633 | tinylmtune._internal.corpus_gen | Generated 200 / 1000 examples (193 valid so far)
2026-05-18 07:01:53,928 | tinylmtune._internal.corpus_gen | Generated 250 / 1000 examples (242 valid so far)
2026-05-18 07:02:11,043 | tinylmtune._internal.corpus_gen | Generated 300 / 1000 examples (290 valid so far)
2026-05-18 07:02:31,544 | tinylmtune._internal.corpus_gen | Generated 350 / 1000 examples (340 valid so far)
2026-05-18 07:02:49,004 | tinylmtune._internal.corpus_gen | Generated 400 / 1000 examples (390 valid so far)
2026-05-18 07:03:08,291 | tinylmtune._internal.corpus_gen | Generated 450 / 1000 examples (439 valid so far)
2026-05-18 07:03:27,709 | tinylmtune._internal.corpus_gen | Generated 500 / 1000 examples (488 valid so far)
2026-05-18 07:03:46,782 | tinylmtune._internal.corpus_gen | Generated 550 / 1000 examples (536 valid so far)
2026-05-18 07:04:08,328 | tinylmtune._internal.corpus_gen | Generated 600 / 1000 examples (585 valid so far)
2026-05-18 07:04:29,247 | tinylmtune._internal.corpus_gen | Generated 650 / 1000 examples (633 valid so far)
2026-05-18 07:04:49,601 | tinylmtune._internal.corpus_gen | Generated 700 / 1000 examples (683 valid so far)
2026-05-18 07:05:09,305 | tinylmtune._internal.corpus_gen | Generated 750 / 1000 examples (732 valid so far)
2026-05-18 07:05:28,281 | tinylmtune._internal.corpus_gen | Generated 800 / 1000 examples (782 valid so far)
2026-05-18 07:05:46,999 | tinylmtune._internal.corpus_gen | Generated 850 / 1000 examples (830 valid so far)
2026-05-18 07:06:06,372 | tinylmtune._internal.corpus_gen | Generated 900 / 1000 examples (879 valid so far)
2026-05-18 07:06:28,008 | tinylmtune._internal.corpus_gen | Generated 950 / 1000 examples (928 valid so far)
2026-05-18 07:06:48,811 | tinylmtune._internal.corpus_gen | Generated 1000 / 1000 examples (978 valid so far)
2026-05-18 07:06:48,837 | tinylmtune._internal.llm_backend | Unloaded LLM: google/flan-t5-small
2026-05-18 07:06:48,841 | tinylmtune._internal.corpus_gen | Saved 978 records → /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/qna_synthetic/corpus.jsonl
2026-05-18 07:06:49,111 | tinylmtune._internal.token_analyzer | Token analysis: n=978 min=6 mean=16 p95=24 max=56 → max_len=24, ga_choices=[16, 24, 64]
2026-05-18 07:06:49,114 | tinylmtune._internal.pipeline | Token analysis: p50=15 p95=24 max=56 → fixed max_len=24
2026-05-18 07:06:49,114 | tinylmtune._internal.dataset | Using 978 user-provided records
2026-05-18 07:06:49,556 | tinylmtune._internal.dataset | Dataset: 782 train, 196 val
2026-05-18 07:06:49,556 | tinylmtune._internal.pipeline | Task=qna, num_labels=2, n_train=782
2026-05-18 07:06:49,557 | tinylmtune._internal.pipeline | Fixed max_len=24 | GA search space (11 params): ['learning_rate', 'batch_size', 'epochs', 'warmup_ratio', 'weight_decay', 'dropout', 'attention_dropout', 'gradient_accumulation_steps', 'lr_scheduler_type', 'label_smoothing', 'max_grad_norm']
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:06:49,780 | tinylmtune._internal.trainer | Training: lr=0.00032151626523665245 bs=4 epochs=6 dropout=0.02 attn_drop=0.15 grad_accum=1 scheduler=constant_with_warmup label_smooth=0.003 grad_norm=0.9

2026-05-18 07:07:00,185 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.985364317893982, 'eval_exact_match': 0.30612244897959184, 'eval_start_acc': 0.5510204081632653, 'eval_end_acc': 0.3520408163265306, 'eval_runtime': 0.1826, 'eval_samples_per_second': 1073.227, 'eval_steps_per_second': 268.307, 'epoch': 3.0}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:07:00,410 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-18 07:07:19,717 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.9167511463165283, 'eval_exact_match': 0.41836734693877553, 'eval_start_acc': 0.5816326530612245, 'eval_end_acc': 0.45408163265306123, 'eval_runtime': 0.1818, 'eval_samples_per_second': 1078.217, 'eval_steps_per_second': 269.554, 'epoch': 7.0}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:07:19,937 | tinylmtune._internal.trainer | Training: lr=0.00021419412708598376 bs=16 epochs=4 dropout=0.02 attn_drop=0.08 grad_accum=4 scheduler=cosine_with_restarts label_smooth=0.060 grad_norm=4.1

2026-05-18 07:07:25,276 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.7680916786193848, 'eval_exact_match': 0.3112244897959184, 'eval_start_acc': 0.5816326530612245, 'eval_end_acc': 0.3673469387755102, 'eval_runtime': 0.0611, 'eval_samples_per_second': 3205.954, 'eval_steps_per_second': 212.64, 'epoch': 3.7346938775510203}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:07:25,490 | tinylmtune._internal.trainer | Training: lr=0.00036621723441343984 bs=4 epochs=8 dropout=0.13 attn_drop=0.18 grad_accum=4 scheduler=cosine label_smooth=0.070 grad_norm=0.7

2026-05-18 07:07:42,152 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.9065062999725342, 'eval_exact_match': 0.3469387755102041, 'eval_start_acc': 0.5816326530612245, 'eval_end_acc': 0.4030612244897959, 'eval_runtime': 0.1797, 'eval_samples_per_second': 1090.948, 'eval_steps_per_second': 272.737, 'epoch': 6.0}
2026-05-18 07:07:42,153 | tinylmtune._internal.ga_optimizer | Gen 1/2 — best=0.4184  avg=0.3457  worst=0.3061
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:07:42,386 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-18 07:07:59,007 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.9148000478744507, 'eval_exact_match': 0.4030612244897959, 'eval_start_acc': 0.5867346938775511, 'eval_end_acc': 0.45408163265306123, 'eval_runtime': 0.1799, 'eval_samples_per_second': 1089.769, 'eval_steps_per_second': 272.442, 'epoch': 6.0}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:07:59,229 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=8 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-18 07:08:18,534 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 1.9350268840789795, 'eval_exact_match': 0.3826530612244898, 'eval_start_acc': 0.5816326530612245, 'eval_end_acc': 0.4387755102040816, 'eval_runtime': 0.1792, 'eval_samples_per_second': 1093.931, 'eval_steps_per_second': 273.483, 'epoch': 7.0}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:08:18,748 | tinylmtune._internal.trainer | Training: lr=0.00019306401381548202 bs=4 epochs=10 dropout=0.18 attn_drop=0.06 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=0.8

2026-05-18 07:08:40,663 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 2.0972859859466553, 'eval_exact_match': 0.3877551020408163, 'eval_start_acc': 0.576530612244898, 'eval_end_acc': 0.4336734693877551, 'eval_runtime': 0.185, 'eval_samples_per_second': 1059.25, 'eval_steps_per_second': 264.812, 'epoch': 8.0}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:08:40,883 | tinylmtune._internal.trainer | Training: lr=0.00018085899661262315 bs=4 epochs=10 dropout=0.11 attn_drop=0.09 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=2.0

2026-05-18 07:09:00,146 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 2.1250393390655518, 'eval_exact_match': 0.37244897959183676, 'eval_start_acc': 0.5663265306122449, 'eval_end_acc': 0.40816326530612246, 'eval_runtime': 0.1796, 'eval_samples_per_second': 1091.34, 'eval_steps_per_second': 272.835, 'epoch': 7.0}
2026-05-18 07:09:00,147 | tinylmtune._internal.ga_optimizer | Gen 2/2 — best=0.4031  avg=0.3865  worst=0.3724
2026-05-18 07:09:00,148 | tinylmtune._internal.pipeline | Best config (fitness=0.4184): {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22, 'fitness': 0.41836734693877553}
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at huawei-noah/TinyBERT_General_4L_312D and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2026-05-18 07:09:00,369 | tinylmtune._internal.trainer | Training: lr=0.0001201671422284161 bs=4 epochs=10 dropout=0.11 attn_drop=0.04 grad_accum=4 scheduler=linear label_smooth=0.076 grad_norm=1.2

2026-05-18 07:09:18,286 | tinylmtune._internal.trainer | Eval metrics: {'eval_loss': 2.106714963912964, 'eval_exact_match': 0.3826530612244898, 'eval_start_acc': 0.5918367346938775, 'eval_end_acc': 0.42346938775510207, 'eval_runtime': 0.1897, 'eval_samples_per_second': 1033.175, 'eval_steps_per_second': 258.294, 'epoch': 7.0}
2026-05-18 07:09:19,103 | tinylmtune._internal.inference | Model saved → /home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/qna_synthetic

Best config: {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22, 'fitness': 0.41836734693877553, 'max_len': 24, 'task': 'qna', 'output_dir': '/home/sagemaker-user/SLM/tinylmtune_v2/notebooks/models/qna_synthetic', 'ga_history': [{'generation': 1, 'individual': 0, 'fitness': 0.30612244897959184, 'learning_rate': 0.00032151626523665245, 'batch_size': 4, 'epochs': 6, 'warmup_ratio': 0.073, 'weight_decay': 0.014, 'dropout': 0.02, 'attention_dropout': 0.148, 'gradient_accumulation_steps': 1, 'lr_scheduler_type': 'constant_with_warmup', 'label_smoothing': 0.003, 'max_grad_norm': 0.92}, {'generation': 1, 'individual': 1, 'fitness': 0.41836734693877553, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 1, 'individual': 2, 'fitness': 0.3112244897959184, 'learning_rate': 0.00021419412708598376, 'batch_size': 16, 'epochs': 4, 'warmup_ratio': 0.065, 'weight_decay': 0.0763, 'dropout': 0.02, 'attention_dropout': 0.076, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine_with_restarts', 'label_smoothing': 0.06, 'max_grad_norm': 4.13}, {'generation': 1, 'individual': 3, 'fitness': 0.3469387755102041, 'learning_rate': 0.00036621723441343984, 'batch_size': 4, 'epochs': 8, 'warmup_ratio': 0.024, 'weight_decay': 0.0293, 'dropout': 0.126, 'attention_dropout': 0.177, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine', 'label_smoothing': 0.07, 'max_grad_norm': 0.71}, {'generation': 2, 'individual': 0, 'fitness': 0.4030612244897959, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 2, 'individual': 1, 'fitness': 0.3826530612244898, 'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 8, 'warmup_ratio': 0.028, 'weight_decay': 0.0602, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}, {'generation': 2, 'individual': 2, 'fitness': 0.3877551020408163, 'learning_rate': 0.00019306401381548202, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.0459, 'dropout': 0.184, 'attention_dropout': 0.059, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 0.81}, {'generation': 2, 'individual': 3, 'fitness': 0.37244897959183676, 'learning_rate': 0.00018085899661262315, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.0635, 'dropout': 0.109, 'attention_dropout': 0.092, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.96}], 'ga_generation_stats': [{'generation': 1, 'best_fitness': 0.41836734693877553, 'worst_fitness': 0.30612244897959184, 'avg_fitness': 0.34566326530612246, 'std_fitness': 0.044824702527565256, 'best_config': {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}}, {'generation': 2, 'best_fitness': 0.4030612244897959, 'worst_fitness': 0.37244897959183676, 'avg_fitness': 0.38647959183673475, 'std_fitness': 0.011046242395209672, 'best_config': {'learning_rate': 0.0001201671422284161, 'batch_size': 4, 'epochs': 10, 'warmup_ratio': 0.06, 'weight_decay': 0.065, 'dropout': 0.109, 'attention_dropout': 0.044, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'linear', 'label_smoothing': 0.076, 'max_grad_norm': 1.22}}]}

### Inference on synthetic model

In [17]:
model = TinyInference("models/qna_synthetic")
result = model.predict("What is the capital of France?", context="Paris is capital of France")
print(result)

2026-05-18 07:10:45,745 | tinylmtune._internal.inference | Loaded qna model from models/qna_synthetic
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'answer': 'paris', 'start': 9, 'end': 9}

---
## Example 2 — Benchmark Data (SQuAD)

Uses a real HuggingFace dataset. No Flan-T5 needed.

### Load SQuAD dataset

In [18]:
from datasets import load_dataset
ds = load_dataset("squad", split="train")
ds = ds.shuffle(seed=42).select(range(5000))
benchmark_data = []
for r in ds:
    answer = r["answers"]["text"][0] if r["answers"]["text"] else ""
    if not answer:
        continue
    benchmark_data.append({
        "question": r["question"],
        "context": r["context"],
        "answer": answer,
    })
print(f"Loaded {len(benchmark_data)} records")
print(f"Sample keys: {benchmark_data[0].keys()}")
print(f"Sample Q: {benchmark_data[0]['question']}")
print(f"Sample A: {benchmark_data[0]['answer']}")
print(f"Sample C: {benchmark_data[0]['context'][:100]}...")

Loaded 5000 records
Sample keys: dict_keys(['question', 'context', 'answer'])
Sample Q: What percentage of Egyptians polled support death penalty for those leaving Islam?
Sample A: 84%
Sample C: The Pew Forum on Religion & Public Life ranks Egypt as the fifth worst country in the world for reli...

In [ ]:
print(benchmark_data[0].keys())
print(benchmark_data[0])

### Analyze token lengths

In [ ]:
print_token_analysis(benchmark_data, task="qna")

### Check recommended search space

In [ ]:
print_recommendation(n_samples=len(benchmark_data), task="qna")

In [ ]:
## Use recommended search space 

GA_SEARCH_SPACE = {'learning_rate': (5e-06, 0.001),
 'batch_size': [4, 8, 16, 32],
 'epochs': (2, 8),
 'warmup_ratio': (0.0, 0.3),
 'weight_decay': (0.0, 0.05),
 'dropout': (0.0, 0.2),
 'attention_dropout': (0.0, 0.2),
 'gradient_accumulation_steps': [1, 2, 4, 8],
 'lr_scheduler_type': ['linear',
  'cosine',
  'cosine_with_restarts',
  'constant_with_warmup'],
 'label_smoothing': (0.0, 0.1),
 'max_grad_norm': (0.5, 5.0)}

### Train with GA optimisation

In [ ]:
best = optimize_slm(
    task="qna",
    user_data=benchmark_data,
    max_len=32,
    pop_size=4,
    generations=2,
    output_dir="models/qna_benchmark",
)
print("Best config:", best)

### Visualize GA Results

5 plots showing how the GA searched for the best hyperparameters:
1. **Fitness progress** — best/avg/worst per generation
2. **Parameter scatter** — each param vs fitness (best = red star)
3. **Scheduler comparison** — box plot by LR scheduler type
4. **Config evolution** — how the best config changed over generations
5. **Population heatmap** — all individuals in the last generation

In [ ]:
from tinylmtune import plot_results, print_best_config_table

# Print formatted best config
print_best_config_table(best)

# Generate all 5 plots
figs = plot_results(best, save_dir="plots/benchmark")

### Inference on benchmark model

In [ ]:
model = TinyInference("models/qna_benchmark")
result = model.predict("Who invented the telephone?", context="Alexander Graham Bell invented the telephone in 1876.")
print(result)

---
## Example 3 — Raw User Data

Three sub-examples showing different input formats:
- **3a.** Structured dicts (correct format)
- **3b.** Raw text strings (auto-labelled via Flan-T5)
- **3c.** Wrong-format dicts (auto-detected and converted)

### 3a. Structured dicts (used directly, no Flan-T5)

In [ ]:
my_data = [
    {"question": "What is Python?", "answer": "A high-level programming language"},
    {"question": "Who created Linux?", "answer": "Linus Torvalds"},
    {"question": "What is TinyBERT?", "answer": "A distilled version of BERT"},
    {"question": "What does GA stand for?", "answer": "Genetic Algorithm"},
    {"question": "What is fine-tuning?", "answer": "Adapting a pretrained model to a specific task"},
    {"question": "What is tokenization?", "answer": "Splitting text into tokens for model input"},
    {"question": "What is NLP?", "answer": "Natural Language Processing"},
    {"question": "What is a transformer?", "answer": "A neural network architecture using attention"},
    {"question": "What is BERT?", "answer": "Bidirectional Encoder Representations from Transformers"},
    {"question": "What is overfitting?", "answer": "When a model memorises training data instead of learning patterns"},
    {"question": "What is dropout?", "answer": "Randomly deactivating neurons during training to prevent overfitting"},
    {"question": "What is a loss function?", "answer": "A function that measures how wrong the model predictions are"},
]

best = optimize_slm(
    task="qna",
    user_data=my_data,
    pop_size=4,
    generations=2,
    output_dir="models/qna_user",
)

### 3b. Raw text strings (requires Flan-T5)

In [ ]:
# Raw text — Flan-T5 generates Q&A pairs from it
raw_texts = [
    "The Eiffel Tower was built in 1889 for the World Fair in Paris.",
    "Water boils at 100 degrees Celsius at sea level.",
    "The human body has 206 bones in the adult skeleton.",
    "DNA stands for deoxyribonucleic acid and carries genetic information.",
    "The speed of light is approximately 300,000 kilometers per second.",
    "Mount Everest is the tallest mountain at 8,849 meters above sea level.",
]

best = optimize_slm(
    task="qna",
    user_data=raw_texts,
    pop_size=4,
    generations=1,
    output_dir="models/qna_raw",
)

### 3c. Wrong-format dicts (requires Flan-T5)

In [ ]:
# Dicts with non-standard keys
wrong_format = [
    {"query": "What year was the moon landing?", "response": "1969"},
    {"query": "Who painted the Mona Lisa?", "response": "Leonardo da Vinci"},
    {"query": "What is the largest ocean?", "response": "Pacific Ocean"},
]

best = optimize_slm(
    task="qna",
    user_data=wrong_format,
    pop_size=4,
    generations=1,
    output_dir="models/qna_wrong",
)

### Visualize user data results

In [ ]:
# Plot results from structured data training (Example 3a)
from tinylmtune import plot_results, print_best_config_table
print_best_config_table(best)
figs = plot_results(best, save_dir="plots/user_data")

### Inference

In [ ]:
model = TinyInference("models/qna_user")
result = model.predict("What is dropout?", context="Dropout randomly deactivates neurons during training.")
print(result)

---
## Summary

| Example | Data source | Flan-T5 needed | Best for |
|---------|-------------|---------------|----------|
| Synthetic | Auto-generated | Yes | Quick prototyping |
| Benchmark | SQuAD | No | Reproducible evaluation |
| User data | Your own text | Depends on format | Production use |

The GA searches 11 hyperparameters: `learning_rate`, `batch_size`, `epochs`, `warmup_ratio`, `weight_decay`, `dropout`, `attention_dropout`, `gradient_accumulation_steps`, `lr_scheduler_type`, `label_smoothing`, `max_grad_norm`.

`max_len` is automatically determined from your data's token length distribution (p95 percentile).